### ISSUE TITLE
More Graphics

### ISSUE THREAD

**Issue by StrangerZ667** [Sonaticspink/Pixel-Car-RACIST#12]

**Comment by Sonaticspink** [comment]
### ปุ่มออกเกม
![Exit](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/04fc9662-78c6-4706-83c7-fadaf00bdfa0)

**Comment by Sonaticspink** [comment]
### รถรำตวด
![Uploading POLICZIAE.png…]()

**Comment by Sonaticspink** [comment]
### รถรำตรวจ
![POLICZIAE](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/1728b218-817e-4065-b780-36de21ee6c51)

**Comment by Sonaticspink** [comment]
เดี๋ยวนั่งทำให้
-รถรำตวดเต็มคัน
-warning ป้าย

**Comment by Sonaticspink** [comment]
### รถตำรวจเต็มคันเบิ้มๆ
![asd](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/da9ba709-8be2-4e8e-9e8c-eb34660ccee3)
