### ISSUE TITLE
final test

### ISSUE THREAD

**Issue by Sonaticspink** [Sonaticspink/Pixel-Car-RACIST#13]
ช่วยกันเล่นแบบพิเรนๆ ดูว่าเกมจะบึ้มรึป่าว

**Comment by Chay-c** [comment]
![image_2024-03-01_153059844](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/141809834/eb230d60-be3b-4cb3-99c0-8f3a854ae2e5)
 ลองใช้เมาส์คลิกที่ปุ่มโหมด(โหมดไหนก็ได้)โดยยังไม่กดปุ่ม P
แล้วกดปุ่มเดิมอีกรอบ ให้ปุ่มเป็นสีดั้งเดิม แล้วกดปุ่ม P
เกมจะเริ่มโดยมีแค่รถเหลือง P1 และไม่มีจับเวลา หรืออาจจะมีแต่ล่องหน

**Comment by StrangerZ667** [comment]
ตอนนี้เวอร์ชั่น ที่สุดของที่สุดมีบัคตอนปิดเกม แล้วเสียงอะไรมันขึ้นเต็มเลยก็ไม่รู้ ใครก็ได้ช่วยที ง่วงโคตร
