### ISSUE TITLE
New Car

### ISSUE THREAD

**Issue by StrangerZ667** [Sonaticspink/Pixel-Car-RACIST#6]

**Comment by Sonaticspink** [comment]
![racer](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/ed018413-159a-4df6-b98b-c09dbedd8b77)
![racer2](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/86da1ffa-075f-4bc1-8a30-f50120bcc955)

**Comment by Sonaticspink** [comment]
![racer2](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/3e7e96d1-4ff1-4758-96b1-1e23404dccf9)
![racer](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/638009c7-9182-4707-beca-3cafd6bc8472)
อันนี้เวอร์ชั่นปรับขนาดแล้วใส่ไฟล์เกมได้เลย

สำหรับโหมดtime recordใช้settingตำแหน่งตรงนี้
![image](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/b8656c95-292c-46f8-9a9b-f0abb744a97b)


จะได้ประมาณนี้
![image](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/c67334e0-f633-438d-8168-4550b21e8ccf)

**Comment by Sonaticspink** [comment]
![image](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/26838062-1295-4f36-abe1-c239a1d81910)
อันนี้รถกระดาษ

![racer](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/0f56ba45-c5f8-43f2-9dfa-9888609f736a)
![background](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/276af919-8aaf-412f-8b3b-244d67671b64)
ไฟล์ภาพพร้อม ปล.รถเดี๋ยวไปลงดีเทลให้อีกที

**Comment by Sonaticspink** [comment]
[Dash Mode button.zip](https://github.com/Sonaticspink/Pixel-Car-RACIST/files/14374333/Dash.Mode.button.zip)
ภาพปุ่มDash Mode

**Comment by Sonaticspink** [comment]
[Back to Menu.zip](https://github.com/Sonaticspink/Pixel-Car-RACIST/files/14374431/Back.to.Menu.zip)
ปุ่มBack to Manu

**Comment by Sonaticspink** [comment]
### ปุ่มรั่วๆ
![4](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/d80efda8-1972-4dc3-b17d-b16279245390)
![3](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/95ce91f7-ff93-4e2f-88c5-66f18a314d70)
![2](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/333becdc-7b5d-4d4a-a152-3fda59aac746)
![1](https://github.com/Sonaticspink/Pixel-Car-RACIST/assets/84556521/67e15182-5463-4114-9e9c-fc8576d9c9d7)
