### ISSUE TITLE
New Contents

### ISSUE THREAD

**Issue by StrangerZ667** [Sonaticspink/Pixel-Car-RACIST#8]

**Comment by Sonaticspink** [comment]
Contect เพิ่มเติมถ้าทัน 
-ระบบscoreboard
-กดกลับไปหน้าเมนูเพื่อเล่นอีกรอบ
-เจียวดาวทรงเครื่อง

**Comment by ChanaweeP1** [comment]
[Gay Sound.zip](https://github.com/Sonaticspink/Pixel-Car-RACIST/files/14415332/Gay.Sound.zip)

 Sound เพิ่มเตืมแต่ละ Mode เจ้า
